-- MySQL Script generated by MySQL Workbench
-- Thu 11 Mar 2021 04:37:50 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `url_acesso` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email_recup` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `descricao_perfil` VARCHAR(45) NULL,
  `status_conta` VARCHAR(45) NULL,
  `count_curtiu` INT NULL,
  `count_curtido` INT NULL,
  `foto_perfil` BLOB NULL,
  `flag_usuario_verificado` VARCHAR(45) NULL,
  `tipo_perfil_public_privado` VARCHAR(45) NULL,
  `online` TINYINT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacao` (
  `id_publicacao` INT NOT NULL AUTO_INCREMENT,
  `foto_video` BLOB NULL,
  `horaedata` DATETIME NULL,
  `lista_ids_usuarios_marcados` JSON NULL,
  PRIMARY KEY (`id_publicacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localizacao_generica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localizacao_generica` (
  `id_localizacao` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `tupla_lat_long_alt` VARCHAR(45) NULL,
  `usuario_id_ou_publicacao_id` INT NULL,
  PRIMARY KEY (`id_localizacao`),
  INDEX `usuario_id_idx` (`usuario_id_ou_publicacao_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id_ou_publicacao_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `publicacao_id`
    FOREIGN KEY (`usuario_id_ou_publicacao_id`)
    REFERENCES `mydb`.`publicacao` (`id_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bloqueio_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bloqueio_usuario` (
  `id_bloqueio_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_bloqueou` INT NULL,
  `usuario_id_bloqueado` INT NULL,
  PRIMARY KEY (`id_bloqueio_usuario`),
  INDEX `usuario_id_bloqueou_idx` (`usuario_id_bloqueou` ASC) VISIBLE,
  INDEX `usuario_id_bloqueado_idx` (`usuario_id_bloqueado` ASC) VISIBLE,
  CONSTRAINT `usuario_id_bloqueou`
    FOREIGN KEY (`usuario_id_bloqueou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_bloqueado`
    FOREIGN KEY (`usuario_id_bloqueado`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restringido_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restringido_usuario` (
  `id_restringido_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_restringiu` INT NULL,
  `usuario_id_restringido` INT NULL,
  PRIMARY KEY (`id_restringido_usuario`),
  INDEX `usuario_id_restringiu_idx` (`usuario_id_restringiu` ASC) VISIBLE,
  INDEX `usuario_id_restringido_idx` (`usuario_id_restringido` ASC) VISIBLE,
  CONSTRAINT `usuario_id_restringiu`
    FOREIGN KEY (`usuario_id_restringiu`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_restringido`
    FOREIGN KEY (`usuario_id_restringido`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`container_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`container_publicacao` (
  `id_container_publicacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_publicou` INT NULL,
  `texto_descricao` VARCHAR(200) NULL,
  `lista_ids_publicacao` JSON NULL,
  `horaedata` DATETIME NULL,
  `lista_hashtags` VARCHAR(500) NULL,
  PRIMARY KEY (`id_container_publicacao`),
  INDEX `usuario_id_publicou_idx` (`usuario_id_publicou` ASC) VISIBLE,
  CONSTRAINT `usuario_id_publicou`
    FOREIGN KEY (`usuario_id_publicou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificacao` (
  `id_notificacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_notificou` INT NULL,
  `usuario_id_notificado` INT NULL,
  `flag_visualizado` VARCHAR(45) NULL,
  `tipo_notificacao` VARCHAR(45) NULL,
  `alvo_id` INT NULL,
  PRIMARY KEY (`id_notificacao`),
  INDEX `usuario_id_notificado_idx` (`usuario_id_notificado` ASC) VISIBLE,
  INDEX `usuario_id_notificou_idx` (`usuario_id_notificou` ASC) VISIBLE,
  INDEX `alvo_id_idx` (`alvo_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_notificou`
    FOREIGN KEY (`usuario_id_notificou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_notificado`
    FOREIGN KEY (`usuario_id_notificado`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alvo_usuario_id`
    FOREIGN KEY (`alvo_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alvo_container_pub_id`
    FOREIGN KEY (`alvo_id`)
    REFERENCES `mydb`.`container_publicacao` (`id_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_denuncia` (
  `id_tipo_denuncia` INT NOT NULL AUTO_INCREMENT,
  `codigo_denuncia` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_denuncia`),
  UNIQUE INDEX `codigo_denuncia_UNIQUE` (`codigo_denuncia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`denuncia_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`denuncia_usuarios` (
  `id_denuncia` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_denunciou` INT NULL,
  `usuario_id_denunciado` INT NULL,
  `tipo_denuncia_id` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_denuncia`),
  INDEX `usuario_id_notificou_idx` (`usuario_id_denunciou` ASC) VISIBLE,
  INDEX `usuario_id_notificado_idx` (`usuario_id_denunciado` ASC) VISIBLE,
  INDEX `tipo_denuncia_id_idx` (`tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_denunciou`
    FOREIGN KEY (`usuario_id_denunciou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_denunciado`
    FOREIGN KEY (`usuario_id_denunciado`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_denuncia_id`
    FOREIGN KEY (`tipo_denuncia_id`)
    REFERENCES `mydb`.`tipo_denuncia` (`id_tipo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_salvo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_salvo` (
  `id_item_salvo` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `container_publicacao_id` INT NULL,
  PRIMARY KEY (`id_item_salvo`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `container_publicacao_id_idx` (`container_publicacao_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `container_publicacao_id`
    FOREIGN KEY (`container_publicacao_id`)
    REFERENCES `mydb`.`container_publicacao` (`id_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curtidas_container_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curtidas_container_publicacao` (
  `id_curtidas_container_publicacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_curtiu` INT NULL,
  `container_publicacao_id` INT NULL,
  `horaedata` DATETIME NULL,
  PRIMARY KEY (`id_curtidas_container_publicacao`),
  INDEX `usuario_id_curtiu_idx` (`usuario_id_curtiu` ASC) VISIBLE,
  INDEX `container_publicacao_id_idx` (`container_publicacao_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_curtiu`
    FOREIGN KEY (`usuario_id_curtiu`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `container_publicacao_id`
    FOREIGN KEY (`container_publicacao_id`)
    REFERENCES `mydb`.`container_publicacao` (`id_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentario_container_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario_container_publicacao` (
  `id_comentario_container_publicacao` INT NOT NULL AUTO_INCREMENT,
  `comentario_msg` VARCHAR(45) NULL,
  `container_publicacao_id` INT NULL,
  `usuario_id_comentou` INT NULL,
  `flag_comentario_resposta_comentario_id` INT NULL,
  `horaedata` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comentario_container_publicacao`),
  INDEX `container_publicacao_id_idx` (`container_publicacao_id` ASC) VISIBLE,
  INDEX `usuario_id_comentou_idx` (`usuario_id_comentou` ASC) VISIBLE,
  INDEX `flag_comentario_resposta_comentario_id_idx` (`flag_comentario_resposta_comentario_id` ASC) VISIBLE,
  CONSTRAINT `container_publicacao_id`
    FOREIGN KEY (`container_publicacao_id`)
    REFERENCES `mydb`.`container_publicacao` (`id_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_comentou`
    FOREIGN KEY (`usuario_id_comentou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `flag_comentario_resposta_comentario_id`
    FOREIGN KEY (`flag_comentario_resposta_comentario_id`)
    REFERENCES `mydb`.`comentario_container_publicacao` (`id_comentario_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensagem_privada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mensagem_privada` (
  `id_mensagem_privada` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_remetente` INT NULL,
  `usuario_id_destinatario` INT NULL,
  `corpo_mensagem` VARCHAR(45) NULL,
  `curtido` VARCHAR(45) NULL,
  `denunciado_tipo_denuncia_id` INT NULL,
  `horaedata` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mensagem_privada`),
  INDEX `usuario_id_remetente_idx` (`usuario_id_remetente` ASC) VISIBLE,
  INDEX `usuario_id_destinatario_idx` (`usuario_id_destinatario` ASC) VISIBLE,
  INDEX `tipo_denuncia_id_idx` (`denunciado_tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_remetente`
    FOREIGN KEY (`usuario_id_remetente`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_destinatario`
    FOREIGN KEY (`usuario_id_destinatario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `denunciado_tipo_denuncia_id`
    FOREIGN KEY (`denunciado_tipo_denuncia_id`)
    REFERENCES `mydb`.`tipo_denuncia` (`id_tipo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`denuncia_container_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`denuncia_container_publicacao` (
  `id_denuncia_container_publicacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_denunciou` INT NULL,
  `container_publicacao_id` INT NULL,
  `tipo_denuncia_id` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_denuncia_container_publicacao`),
  INDEX `usuario_id_denunciou_idx` (`usuario_id_denunciou` ASC) VISIBLE,
  INDEX `container_publicacao_id_idx` (`container_publicacao_id` ASC) VISIBLE,
  INDEX `tipo_denuncia_id_idx` (`tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_denunciou`
    FOREIGN KEY (`usuario_id_denunciou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `container_publicacao_id`
    FOREIGN KEY (`container_publicacao_id`)
    REFERENCES `mydb`.`container_publicacao` (`id_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_denuncia_id`
    FOREIGN KEY (`tipo_denuncia_id`)
    REFERENCES `mydb`.`tipo_denuncia` (`id_tipo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguir_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguir_usuario` (
  `id_seguir_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_seguiu` INT NULL,
  `usuario_id_seguido` INT NULL,
  `flag_amigo_favorito` VARCHAR(45) NULL,
  `status_solicitacao_amiz` VARCHAR(45) NULL,
  `silenciou` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seguir_usuario`),
  INDEX `usuario_id_seguiu_idx` (`usuario_id_seguiu` ASC) VISIBLE,
  INDEX `usuario_id_seguido_idx` (`usuario_id_seguido` ASC) VISIBLE,
  CONSTRAINT `usuario_id_seguiu`
    FOREIGN KEY (`usuario_id_seguiu`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_seguido`
    FOREIGN KEY (`usuario_id_seguido`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`story` (
  `id_story` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `link` VARCHAR(45) NULL,
  `publicacao_midia` BLOB NULL,
  `horaedata` DATETIME NULL,
  `story_destaque_label` VARCHAR(45) NULL,
  PRIMARY KEY (`id_story`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentario_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentario_story` (
  `id_comentario_story` INT NOT NULL AUTO_INCREMENT,
  `story_id` INT NULL,
  `usuario_id_comentou` INT NULL,
  `comentario_msg` VARCHAR(45) NULL,
  `flag_comentario_resposta_usuario_id` INT NULL,
  `curtido` VARCHAR(45) NULL,
  `denunciado_tipo_denuncia_id` INT NULL,
  `horaedata` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comentario_story`),
  INDEX `story_id_idx` (`story_id` ASC) VISIBLE,
  INDEX `usuario_id_comentou_idx` (`usuario_id_comentou` ASC) VISIBLE,
  INDEX `flag_comentario_resposta_usuario_id_idx` (`flag_comentario_resposta_usuario_id` ASC) VISIBLE,
  INDEX `denunciado_tipo_denuncia_id_idx` (`denunciado_tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `story_id`
    FOREIGN KEY (`story_id`)
    REFERENCES `mydb`.`story` (`id_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id_comentou`
    FOREIGN KEY (`usuario_id_comentou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `flag_comentario_resposta_usuario_id`
    FOREIGN KEY (`flag_comentario_resposta_usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `denunciado_tipo_denuncia_id`
    FOREIGN KEY (`denunciado_tipo_denuncia_id`)
    REFERENCES `mydb`.`tipo_denuncia` (`id_tipo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuracao_usuario` (
  `id_configuracao_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `regras_notificacao` VARCHAR(45) NULL,
  `regras_privacidade` VARCHAR(45) NULL,
  `regras_seguranca` VARCHAR(45) NULL,
  `regras_anuncios` VARCHAR(45) NULL,
  `configuracao_conta` VARCHAR(45) NULL,
  PRIMARY KEY (`id_configuracao_usuario`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curtida_coment_container_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curtida_coment_container_publicacao` (
  `id_curtida_coment_container_publicacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `comentario_container_publicacao_id` INT NULL,
  `horaedata` VARCHAR(45) NULL,
  PRIMARY KEY (`id_curtida_coment_container_publicacao`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `comentario_container_publicacao_id_idx` (`comentario_container_publicacao_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comentario_container_publicacao_id`
    FOREIGN KEY (`comentario_container_publicacao_id`)
    REFERENCES `mydb`.`comentario_container_publicacao` (`id_comentario_container_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seguir_hashtag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguir_hashtag` (
  `id_seguir_hashtag` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `descricao_hashtag` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seguir_hashtag`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`view_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_story` (
  `id_view_story` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_visualizou` INT NULL,
  `story_id` INT NULL,
  `horaedata` DATETIME NULL,
  PRIMARY KEY (`id_view_story`),
  INDEX `usuario_id_visualizou_idx` (`usuario_id_visualizou` ASC) VISIBLE,
  INDEX `story_id_idx` (`story_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_visualizou`
    FOREIGN KEY (`usuario_id_visualizou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `story_id`
    FOREIGN KEY (`story_id`)
    REFERENCES `mydb`.`story` (`id_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`views_publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`views_publicacao` (
  `id_views_publicacao` INT NOT NULL AUTO_INCREMENT,
  `publicacao_id` INT NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id_views_publicacao`),
  INDEX `publicacao_id_idx` (`publicacao_id` ASC) VISIBLE,
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `publicacao_id`
    FOREIGN KEY (`publicacao_id`)
    REFERENCES `mydb`.`publicacao` (`id_publicacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_tempo_utilizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_tempo_utilizacao` (
  `id_historico_tempo_utilizacao` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `logon_logout` VARCHAR(45) NULL,
  `dataehora` DATETIME NULL,
  PRIMARY KEY (`id_historico_tempo_utilizacao`),
  INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`denuncia_story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`denuncia_story` (
  `id_denuncia_story` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_denunciou` INT NULL,
  `story_id_denunciado` INT NULL,
  `tipo_denuncia_id` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_denuncia_story`),
  INDEX `usuario_id_denunciou_idx` (`usuario_id_denunciou` ASC) VISIBLE,
  INDEX `story_id_denunciado_idx` (`story_id_denunciado` ASC) VISIBLE,
  INDEX `tipo_denuncia_id_idx` (`tipo_denuncia_id` ASC) VISIBLE,
  CONSTRAINT `usuario_id_denunciou`
    FOREIGN KEY (`usuario_id_denunciou`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `story_id_denunciado`
    FOREIGN KEY (`story_id_denunciado`)
    REFERENCES `mydb`.`story` (`id_story`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_denuncia_id`
    FOREIGN KEY (`tipo_denuncia_id`)
    REFERENCES `mydb`.`tipo_denuncia` (`id_tipo_denuncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
